name: reboot_cli
description: Command Line Interface for Project Reboot
version: "10.0.7"

publish_to: 'none'

environment:
  sdk: ">=2.19.0 <=3.5.3"

dependencies:
  reboot_common:
    path: ./../common
  tint: ^2.0.1
  interact: ^2.2.0
  args: ^2.6.0

dependency_overrides:
  xml: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.1