name: reboot_cli
description: Command Line Interface for Project Reboot
version: "10.0.7"

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <=3.5.3"

dependencies:
  reboot_common:
    path: ./../common
  tint: ^2.0.1
  interact_cli: ^2.4.0
  args: ^2.6.0
  version: ^3.0.2

dependency_overrides:
  xml: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.1